# Generated by Django 4.0.4 on 2022-07-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('group_alias', models.CharField(max_length=255)),
                ('group_under', models.CharField(max_length=255)),
                ('nature', models.CharField(max_length=255, null=True)),
                ('gross_profit', models.CharField(max_length=255, null=True)),
                ('sub_ledger', models.CharField(max_length=255)),
                ('debit_credit', models.CharField(max_length=255)),
                ('calculation', models.CharField(max_length=255)),
                ('invoice', models.CharField(max_length=255)),
            ],
        ),
    ]
