# Generated by Django 4.0.4 on 2022-07-26 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alt_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='tally_tds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tan_reg_no', models.CharField(max_length=40)),
                ('tax_ded_clctn', models.CharField(max_length=40)),
                ('deductor_type', models.CharField(max_length=100)),
                ('ded_brachdevision', models.CharField(max_length=255)),
                ('person_res', models.CharField(max_length=255)),
                ('ignore_it', models.CharField(max_length=40)),
                ('tds_stock_items', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='person_res_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('son_daughter', models.CharField(max_length=255, null=True)),
                ('designation', models.CharField(max_length=255, null=True)),
                ('pan', models.CharField(max_length=255, null=True)),
                ('flat_no', models.CharField(max_length=10, null=True)),
                ('premise_name', models.CharField(max_length=255, null=True)),
                ('street', models.CharField(max_length=255, null=True)),
                ('area', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('mobile_no', models.IntegerField(null=True)),
                ('std_code', models.IntegerField(null=True)),
                ('telephone', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('tds', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tally_tds')),
            ],
        ),
    ]
