# Generated by Django 4.0.4 on 2022-08-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_tally_ledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally_ledger',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
