# Generated by Django 4.0.4 on 2022-08-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_tally_ledger_ledger_bankac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tally_ledger',
            old_name='SA_gst',
            new_name='opening_blnc',
        ),
    ]
