# Generated by Django 4.0.4 on 2022-08-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_tally_ledger_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person_res_details',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person_res_details',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person_res_details',
            name='mobile_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='person_res_details',
            name='pincode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person_res_details',
            name='std_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='person_res_details',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person_res_details',
            name='telephone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
