# Generated by Django 4.0.4 on 2022-07-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_vouchers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vouchers',
            old_name='name',
            new_name='voucher_name',
        ),
    ]
