# Generated by Django 4.0.4 on 2022-08-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_sa_gst_tally_ledger_opening_blnc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger_bankac',
            name='acc_nm',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
