# Generated by Django 4.0.4 on 2022-08-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_create_company_fax_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tally_currency',
            new_name='crt_currency',
        ),
    ]
