# Generated by Django 4.0.4 on 2022-07-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_name_vouchers_voucher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tally_vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.CharField(max_length=255, null=True)),
                ('alias', models.CharField(max_length=255, null=True)),
                ('voucher_type', models.CharField(max_length=255, null=True)),
                ('Abbreviation', models.CharField(max_length=255, null=True)),
                ('activate_Vtype', models.CharField(max_length=20, null=True)),
                ('method_Vno', models.CharField(max_length=200, null=True)),
                ('prevent', models.CharField(max_length=20, null=True)),
                ('advance_con', models.CharField(max_length=20, null=True)),
                ('use_EDV', models.CharField(max_length=20, null=True)),
                ('zero_val', models.CharField(max_length=20, null=True)),
                ('mVoptional_defualt', models.CharField(max_length=20, null=True)),
                ('allow_nar', models.CharField(max_length=20, null=True)),
                ('provide_L', models.CharField(max_length=20, null=True)),
                ('manu_jrnl', models.CharField(max_length=20, null=True)),
                ('track_purchase', models.CharField(max_length=20, null=True)),
                ('enable_acc', models.CharField(max_length=20, null=True)),
                ('prnt_VA_save', models.CharField(max_length=20, null=True)),
                ('prnt_frml', models.CharField(max_length=20, null=True)),
                ('jurisdiction', models.CharField(max_length=20, null=True)),
                ('title_print', models.CharField(max_length=20, null=True)),
                ('set_alter', models.CharField(max_length=20, null=True)),
                ('pos_invoice', models.CharField(max_length=20, null=True)),
                ('msg_1', models.CharField(max_length=255, null=True)),
                ('msg_2', models.CharField(max_length=255, null=True)),
                ('default_bank', models.CharField(max_length=255, null=True)),
                ('name_class', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
