# Generated by Django 4.0.4 on 2022-08-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_tally_currency_crt_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_company',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
