# Generated by Django 4.0.4 on 2022-08-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_creategodown_gst_stockitem_pancin_price_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst',
            name='threshold_limit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gst',
            name='threshold_limit2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
