# Generated by Django 4.0.4 on 2022-08-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_acc_nm_ledger_bankac_acc_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally_ledger',
            name='Echeque_p',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tally_ledger',
            name='SA_chequeP_con',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tally_ledger',
            name='SA_cheque_bk',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tally_ledger',
            name='ac_holder_nm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tally_ledger',
            name='acc_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tally_ledger',
            name='bank_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tally_ledger',
            name='branch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tally_ledger',
            name='ifsc_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tally_ledger',
            name='set_odl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tally_ledger',
            name='swift_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ledger_bankac',
        ),
    ]
