# Generated by Django 4.0.4 on 2022-08-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_gst_threshold_limit_alter_gst_threshold_limit2'),
    ]

    operations = [
        migrations.CreateModel(
            name='unitcreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('formal_name', models.CharField(max_length=100)),
                ('uqc', models.CharField(max_length=100)),
                ('decimal', models.IntegerField()),
                ('f_unit', models.CharField(max_length=100, null=True)),
                ('conversion', models.IntegerField()),
                ('s_unit', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
