# Generated by Django 4.0.4 on 2022-08-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_tally_ledger_echeque_p_tally_ledger_sa_chequep_con_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tally_ledger',
            name='opening_blnc',
            field=models.IntegerField(),
        ),
    ]
