# Generated by Django 4.0.4 on 2022-07-30 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_gst_taxability_applicable_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='currency_ROE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ROE', models.DateField()),
                ('std_rate', models.CharField(max_length=20, null=True)),
                ('selling_SR', models.CharField(max_length=20, null=True)),
                ('buying_SR', models.CharField(max_length=20, null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tally_currency')),
            ],
        ),
    ]
