# Generated by Django 4.0.4 on 2022-08-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_unitcreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitcreation',
            name='conversion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='unitcreation',
            name='decimal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='unitcreation',
            name='formal_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unitcreation',
            name='symbol',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unitcreation',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unitcreation',
            name='uqc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
