# Generated by Django 4.0.4 on 2022-08-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_unitcreation_conversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitcreation',
            name='conversion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unitcreation',
            name='decimal',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
