# Generated by Django 4.0.4 on 2022-08-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_ledger_cheque_demension'),
    ]

    