# Generated by Django 4.0.4 on 2022-08-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_unitcreation_conversion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit_compound',
            name='unit_simple',
        ),
        migrations.AddField(
            model_name='unit_compound',
            name='f_unit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unit_compound',
            name='s_unit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
