# Generated by Django 4.0.4 on 2022-08-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_ledger_bankdetails_b_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_companies',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
