# Generated by Django 4.0.4 on 2022-08-31 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_unit_compound_unit_simple_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='unitcreation',
        ),
    ]
