# Generated by Django 4.0.4 on 2022-08-10 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_create_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintain_account', models.CharField(max_length=10)),
                ('billwise_entry', models.CharField(max_length=10)),
                ('cost_centre', models.CharField(max_length=10)),
                ('interest_calculation', models.CharField(max_length=10)),
                ('maintain_inventry', models.CharField(max_length=10)),
                ('account_inventry', models.CharField(max_length=10)),
                ('multiple_pricelevel', models.CharField(max_length=10)),
                ('enable_batches', models.CharField(max_length=10)),
                ('expiry_date', models.CharField(max_length=10)),
                ('job_order_procress', models.CharField(max_length=10)),
                ('cost_tracking', models.CharField(max_length=10)),
                ('job_costing', models.CharField(max_length=10)),
                ('discount_column', models.CharField(max_length=10)),
                ('seperte_actual', models.CharField(max_length=10)),
                ('gst', models.CharField(max_length=10)),
                ('tds', models.CharField(max_length=10)),
                ('tcs', models.CharField(max_length=10)),
                ('vat', models.CharField(max_length=10)),
                ('excise', models.CharField(max_length=10)),
                ('service_tax', models.CharField(max_length=10)),
                ('payroll', models.CharField(max_length=10)),
                ('multiple_address', models.CharField(max_length=10)),
                ('mark_modified', models.CharField(max_length=10)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.create_company')),
            ],
        ),
    ]
