# Generated by Django 4.0.4 on 2022-08-20 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_ledger_bankdetails_b_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost_centre',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.create_companies'),
        ),
    ]
