# Generated by Django 4.0.4 on 2022-08-31 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_delete_unitcreation'),
    ]

    operations = [
        migrations.CreateModel(
            name='uqcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uqc_name', models.CharField(max_length=100)),
            ],
        ),
    ]
