# Generated by Django 4.0.4 on 2022-08-20 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_cost_centre_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='tally_group',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.create_companies'),
        ),
    ]
