# Generated by Django 4.0.4 on 2022-08-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_currency_roe_currency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_roe',
            name='buying_SR',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='currency_roe',
            name='selling_SR',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='currency_roe',
            name='std_rate',
            field=models.IntegerField(null=True),
        ),
    ]
