# Generated by Django 4.0.4 on 2022-09-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_uqcs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_item',
            name='stockgroupcreation',
        ),
        migrations.RemoveField(
            model_name='stock_item',
            name='unit_compound',
        ),
        migrations.AddField(
            model_name='stock_item',
            name='batches',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stock_item',
            name='cost_tracking',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stock_item',
            name='under',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stock_item',
            name='units',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock_item',
            name='gst_applicable',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
