# Generated by Django 4.0.4 on 2022-08-20 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_tally_group_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='create_company',
        ),
    ]
