# Generated by Django 4.0.4 on 2022-08-10 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_currency_roe_buying_sr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency_roe',
            name='currency',
        ),
        migrations.AlterField(
            model_name='currency_roe',
            name='currency_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.tally_currency'),
        ),
    ]
