# Generated by Django 4.0.4 on 2022-09-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_rename_name1_stock_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_level',
            name='number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
