# Generated by Django 4.0.4 on 2022-08-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency_roe',
            name='buying_SR',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currency_roe',
            name='selling_SR',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currency_roe',
            name='std_rate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
