# Generated by Django 4.0.4 on 2022-08-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_currency_roe_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ledger_bankdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=100)),
                ('cross_using', models.CharField(max_length=100)),
                ('acc_no', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
            ],
        ),
    ]
