# Generated by Django 4.0.4 on 2022-08-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_ledger_bankdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ledger_chequebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.IntegerField()),
                ('to_number', models.IntegerField()),
                ('no_of_cheques', models.IntegerField()),
                ('cheque_bookname', models.CharField(max_length=100)),
            ],
        ),
    ]
