# Generated by Django 4.0.4 on 2022-08-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_ledger_gst'),
    ]

    operations = [
        migrations.CreateModel(
            name='ledger_gstvalues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature_of_transaction', models.CharField(max_length=255)),
                ('taxable', models.CharField(max_length=100, null=True)),
                ('taxability', models.CharField(max_length=100, null=True)),
                ('appicable_from', models.DateField(null=True)),
                ('integrated_tax', models.CharField(max_length=100, null=True)),
                ('cess', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
