# Generated by Django 4.0.4 on 2022-08-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_ledger_gstvalues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ledger_gst',
        ),
    ]
