# Generated by Django 4.0.4 on 2022-08-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_remove_ledger_cheque_demension_ledger_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='voucher_advanceconf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_no', models.IntegerField()),
                ('numerical_partwidth', models.IntegerField()),
                ('prefill_zero', models.CharField(max_length=10)),
                ('restart_applicable_dt', models.DateField()),
                ('restart_startingno', models.IntegerField()),
                ('restart_particular', models.CharField(max_length=100)),
                ('prefix_applicable_dt', models.DateField()),
                ('prefix_particular', models.CharField(max_length=100)),
                ('suffix_applicable_dt', models.DateField()),
                ('suffix_particular', models.CharField(max_length=100)),
            ],
        ),
    ]
