# Generated by Django 4.0.4 on 2022-08-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_voucher_advanceconf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ledger_taxgst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(max_length=255)),
                ('assessee_teritory', models.CharField(max_length=10)),
                ('commerce_operator', models.CharField(max_length=10)),
                ('party_deemed', models.CharField(max_length=10)),
                ('party_type', models.CharField(max_length=100)),
                ('gstin_uin', models.CharField(max_length=100)),
                ('transporter', models.CharField(max_length=10)),
                ('transporter_id', models.CharField(max_length=100)),
            ],
        ),
    ]
