# Generated by Django 4.0.4 on 2022-08-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_ledger_taxgst'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ledger_taxgst',
            new_name='ledger_taxreggst',
        ),
    ]
