# Generated by Django 4.0.4 on 2022-08-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_rename_ledger_taxgst_ledger_taxreggst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger_taxreggst',
            name='transporter_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
